os:
  - windows
  - linux
  - osx
language: csharp
solution: GianLuca.Domain.Core.sln
mono: none
dotnet: 2.0.0
dist: trusty
before_install:
<<<<<<< HEAD
=======
  - nuget restore
>>>>>>> afb464bc77e7a49b0221790db6ac182da96a3465
  - choco install opencover.portable
  - choco install codecov
  - chmod +x codecov.sh
  - cd .travis/
  - chmod +x build.sh
  - chmod +x test.sh
script:
  - sudo ./build.sh --quiet verify
  - sudo ./test.sh --quiet verify
  - cd ../
  - sudo ./codecov.sh
