os:
  - windows
  - linux
  - osx
language: csharp
solution: GianLuca.Domain.Core.sln
mono: none
dotnet: 2.1.0
dist: trusty
before_install:
  - cd .travis/
  - chmod +x build.sh
  - chmod +x test.sh
script:
  - sudo ./build.sh --quiet verify
  - sudo ./test.sh --quiet verify
  - grep "Test Results" build.log
