using System;
using GianLuca.Domain.Core.Entity;
using Xunit;

namespace GianLuca.Domain.Core.UnitTest
{
    public class BaseEntityTest
    {
        [Fact]
        public void AutoGeneratedGuid()
        {
            //Arrange
            var entity = new BaseEntity();

            //Act
            var isEmpty = entity.Id != Guid.Empty;

            //Verify
            Assert.True(isEmpty);
        }

        [Fact]
        public void CtorPassedGuid()
        {
            //Arrange
            var generatedGuid = Guid.NewGuid();

            //Act
            var entity = new BaseEntity(generatedGuid);

            //Verify
            Assert.Equal(generatedGuid, entity.Id);
        }
    }
}
