using System;
using GianLuca.Domain.Core.Entity;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace GianLuca.Domain.Core.UnitTest
{
    [TestClass]
    public class BaseEntityTest
    {
        [TestMethod]
        public void AutoGeneratedGuid()
        {
            //Arrange
            var entity = new BaseEntity();

            //Act
            var isEmpty = entity.Id != Guid.Empty;

            //Verify
            Assert.IsTrue(isEmpty);
        }

        [TestMethod]
        public void CtorPassedGuid()
        {
            //Arrange
            var generatedGuid = Guid.NewGuid();

            //Act
            var entity = new BaseEntity(generatedGuid);

            //Verify
            Assert.AreEqual(generatedGuid, entity.Id);
        }
    }
}
