using System;
using GianLuca.Domain.Core.ViewModel;
using Xunit;

namespace GianLuca.Domain.Core.UnitTest
{
    public class BaseViewModelTest
    {
        [Fact]
        public void AutoGeneratedGuidWorked()
        {
            //Arrange
            var entity = new BaseViewModel();

            //Act
            var isEmpty = entity.Id != Guid.Empty;

            //Verify
            Assert.True(isEmpty);
        }

        [Fact]
        public void AutoGeneratedGuidNotWorked()
        {
            //Arrange
            var entity = new BaseViewModel();

            //Act
            var isFull = entity.Id == Guid.Empty;

            //Verify
            Assert.False(isFull);
        }
    }
}
